package com.example.HealthyCampus.greendao;

import com.example.HealthyCampus.greendao.model.PatienInforBean;
import com.example.HealthyCampus.greendao.model.SearchAdd;
import com.example.HealthyCampus.greendao.model.SearchBook;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig patienInforBeanDaoConfig;
    private final DaoConfig searchAddDaoConfig;
    private final DaoConfig searchBookDaoConfig;

    private final PatienInforBeanDao patienInforBeanDao;
    private final SearchAddDao searchAddDao;
    private final SearchBookDao searchBookDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        patienInforBeanDaoConfig = daoConfigMap.get(PatienInforBeanDao.class).clone();
        patienInforBeanDaoConfig.initIdentityScope(type);

        searchAddDaoConfig = daoConfigMap.get(SearchAddDao.class).clone();
        searchAddDaoConfig.initIdentityScope(type);

        searchBookDaoConfig = daoConfigMap.get(SearchBookDao.class).clone();
        searchBookDaoConfig.initIdentityScope(type);

        patienInforBeanDao = new PatienInforBeanDao(patienInforBeanDaoConfig, this);
        searchAddDao = new SearchAddDao(searchAddDaoConfig, this);
        searchBookDao = new SearchBookDao(searchBookDaoConfig, this);

        registerDao(PatienInforBean.class, patienInforBeanDao);
        registerDao(SearchAdd.class, searchAddDao);
        registerDao(SearchBook.class, searchBookDao);
    }
    
    public void clear() {
        patienInforBeanDaoConfig.clearIdentityScope();
        searchAddDaoConfig.clearIdentityScope();
        searchBookDaoConfig.clearIdentityScope();
    }

    public PatienInforBeanDao getPatienInforBeanDao() {
        return patienInforBeanDao;
    }

    public SearchAddDao getSearchAddDao() {
        return searchAddDao;
    }

    public SearchBookDao getSearchBookDao() {
        return searchBookDao;
    }

}
