package com.example.HealthyCampus.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig friendDaoConfig;
    private final DaoConfig friendRequestDaoConfig;
    private final DaoConfig chatSessionDaoConfig;
    private final DaoConfig chatItemDaoConfig;

    private final FriendDao friendDao;
    private final FriendRequestDao friendRequestDao;
    private final ChatSessionDao chatSessionDao;
    private final ChatItemDao chatItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        friendDaoConfig = daoConfigMap.get(FriendDao.class).clone();
        friendDaoConfig.initIdentityScope(type);

        friendRequestDaoConfig = daoConfigMap.get(FriendRequestDao.class).clone();
        friendRequestDaoConfig.initIdentityScope(type);

        chatSessionDaoConfig = daoConfigMap.get(ChatSessionDao.class).clone();
        chatSessionDaoConfig.initIdentityScope(type);

        chatItemDaoConfig = daoConfigMap.get(ChatItemDao.class).clone();
        chatItemDaoConfig.initIdentityScope(type);

        friendDao = new FriendDao(friendDaoConfig, this);
        friendRequestDao = new FriendRequestDao(friendRequestDaoConfig, this);
        chatSessionDao = new ChatSessionDao(chatSessionDaoConfig, this);
        chatItemDao = new ChatItemDao(chatItemDaoConfig, this);

        registerDao(Friend.class, friendDao);
        registerDao(FriendRequest.class, friendRequestDao);
        registerDao(ChatSession.class, chatSessionDao);
        registerDao(ChatItem.class, chatItemDao);
    }
    
    public void clear() {
        friendDaoConfig.getIdentityScope().clear();
        friendRequestDaoConfig.getIdentityScope().clear();
        chatSessionDaoConfig.getIdentityScope().clear();
        chatItemDaoConfig.getIdentityScope().clear();
    }

    public FriendDao getFriendDao() {
        return friendDao;
    }

    public FriendRequestDao getFriendRequestDao() {
        return friendRequestDao;
    }

    public ChatSessionDao getChatSessionDao() {
        return chatSessionDao;
    }

    public ChatItemDao getChatItemDao() {
        return chatItemDao;
    }

}
